version: "3"
services:
  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
      MYSQL_USER: hotel
      MYSQL_PASSWORD: hotel
    ports:
      - 3306:3306